[workspace]
resolver = "2"
members = ["crates/leptos-tw-ui", "site"]
# exclude = ["site"]

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
leptos-tw-ui = { path = "crates/leptos-tw-ui", default-features = false }
site = { path = "./site", default-features = false }
