[build]
target = "site/index.html"
dist = "site/dist"

[[hooks]]
stage = "pre_build"
# command = "sh"
# command_arguments = ["-c", "npx tailwindcss -i style/input.css -o style/output.css"]
command = "npm"
command_arguments = ["run", "tw:release"]
